### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by SeekPoint** [JuneFeng/RelationClassification-RL#8]
mldl@ub1604:~/ub16_prj/RelationClassification-RL$ ./main rlpre 0.01
wordTotal=	114042
Word dimension=	50
Segmentation fault (core dumped)
mldl@ub1604:~/ub16_prj/RelationClassification-RL$ ./main r 0.01
mldl@ub1604:~/ub16_prj/RelationClassification-RL$ ./main rl 0.01
wordTotal=	114042
Word dimension=	50
Segmentation fault (core dumped)
mldl@ub1604:~/ub16_prj/RelationClassification-RL$ ./main test
wordTotal=	114042
Word dimension=	50
Segmentation fault (core dumped)
mldl@ub1604:~/ub16_prj/RelationClassification-RL$

**Comment by JunKuang-algo** [comment]
> mldl@ub1604:~/ub16_prj/RelationClassification-RL$ ./main rlpre 0.01 wordTotal=	114042 Word dimension=	50 Segmentation fault (core dumped) mldl@ub1604:~/ub16_prj/RelationClassification-RL$ ./main r 0.01
> mldl@ub1604:~/ub16_prj/RelationClassification-RL$ ./main rl 0.01 wordTotal=	114042 Word dimension=	50 Segmentation fault (core dumped) mldl@ub1604:~/ub16_prj/RelationClassification-RL$ ./main test
> wordTotal=	114042
> Word dimension=	50
> Segmentation fault (core dumped)
> mldl@ub1604:~/ub16_prj/RelationClassification-RL$

Hi, @loveJasmine 
Have you solved this problem?

**Comment by ShellingFord221** [comment]
Hi, I have encountered the same problem that the model can't be tested. Have you guys solved this problem? Thanks!

**Comment by ShellingFord221** [comment]
Besides, after I train the model, there is nothing in out/rlpre/pr.txt, which I really wonder why.
